package com.challenge.api.dto;

import java.time.Instant;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for creating a new Employee.
 * Used as the request body for the createEmployee endpoint.
 * UUID and fullName are not included as they are generated by the service.
 */
@Data
@NoArgsConstructor
public class CreateEmployeeRequest {
    private String firstName;
    private String lastName;
    private Integer salary;
    private Integer age;
    private String jobTitle;
    private String email;
    private Instant contractHireDate;
    private Instant contractTerminationDate;
}
